### ISSUE TITLE
Unable to build the app in Xcode 16.0 Beta 5 and in macOS 15.0 Beta

### ISSUE THREAD

**Issue by sekharchandra** [huggingface/swift-chat#20]
The following is the error : 

Mutable capture of 'inout' parameter 'buffer' is not allowed in concurrently-executing code.

![Screenshot 2024-08-08 at 5 44 22 PM](https://github.com/user-attachments/assets/a6b5f4bb-54d9-4f6d-af61-0d25326c0150)

**Comment by pcuenca** [comment]
Fixed in `swift-transformers` `preview` branch. Can you please try to update to the latest package versions, @sekharchandra?

**Comment by pcuenca** [comment]
Closing for now, please reopen if necessary!
