### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by 1063910011** [huggingface/swift-chat#23]
![image](https://github.com/user-attachments/assets/be765c5d-12c7-4508-95ea-bb7701a29e81)

**Comment by pcuenca** [comment]
Hello @1063910011. The `preview` branch, which you seem to be compiling, requires beta versions of macOS and Xcode. Could you please specify the versions you are using?

**Comment by 1063910011** [comment]
Yes, I use beta versions of MacOS 15.0 and  Xcode Version 16.1, but build failed. 
![image](https://github.com/user-attachments/assets/972fdfb0-b4c2-4306-b300-941a5604c3d8)

---
Luckily, ios is build succeeded, but get another error when run the StatefulMistral7BInstructInt4.mlpackage .
```swift
Error Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow 
fragments not set. around line 1, column 0." UserInfo={NSDebugDescription=JSON text did not start with array or object and 
option to allow fragments not set. around line 1, column 0., NSJSONSerializationErrorIndex=0}
```
Ios version is iOS 18.1 (22B5023e)

![image](https://github.com/user-attachments/assets/3d3bab40-81e5-4120-94bc-bbddcb56b537)

**Comment by pcuenca** [comment]
Hi @1063910011. A couple of notes about the experimental `preview` branch:

- For Mac, it requires Apple Silicon (so M1 or better).
- It hasn't been tested on iOS.

Regarding the issue you reported, it could be the case (but I'm not sure) that you need to launch the app setting the environment variable `HUGGING_FACE_HUB_TOKEN` with your [Hugging Face token](https://huggingface.co/settings/tokens). This is because the tokenizer is retrieved from the [original model repo](https://hf.co/mistralai/Mistral-7B-Instruct-v0.3), which requires authenticated access.

**Comment by 1063910011** [comment]
Helpful, it works after I set the environment variable `HUGGING_FACE_HUB_TOKEN`

But it is very slow on the iPhone 15 Promax. It seems to be computed by CPU and GPU only by default.
![image](https://github.com/user-attachments/assets/f0706957-8063-49e3-830f-6b4cbee9e530)

---

 I am trying to modify `computeUnits` to `.all` to load model, then load failed, get error: no model could be loaded.  I selected the same model StatefulMistral7BInstructInt4.mlpackage 
![image](https://github.com/user-attachments/assets/d8235fc1-8194-452e-928c-c50175fa55a7)

**Comment by sekharchandra** [comment]
<img width="1041" alt="Screenshot 2024-08-16 at 11 58 41 AM" src="https://github.com/user-attachments/assets/5e18fb04-a03b-40a9-8597-db2eb6664da0">

Hi There, Even after adding the HUGGING_FACE_HUB_TOKEN, unable to generate the content. Anything am I missing?

**Comment by pcuenca** [comment]
Hi @sekharchandra, it should work with the envvar as @1063910011 reported. You need to add it here:

<img width="926" alt="Screenshot 2024-08-16 at 09 44 32" src="https://github.com/user-attachments/assets/1e76f608-dcdc-465a-8c6d-c4d0f3a8904a">

Regarding iOS, the model has been optimized for GPU on Mac. Good performance on iPhone would require making it compatible with Neural Engine, we'll be running some tests soon!

**Comment by pcuenca** [comment]
The original issue (build error) is fixed, closing this now. Feel free to open additional issues for discussion as you need to!
