### ISSUE TITLE
Command CompileAssetCatalog failed with a nonzero exit code

### ISSUE THREAD

**Issue by sidan5** [huggingface/swift-chat#6]
When trying to run the project I get this error....

**Comment by ericlewis** [comment]
There is something up with the project file. If you simply delete the App Icon text in the SS (already removed it), then it will build.

<img width="663" alt="Screenshot 2023-11-26 at 8 55 21 AM" src="https://github.com/huggingface/swift-chat/assets/674503/5f72a591-d0cb-4d54-a15f-301139a06e72">

**Comment by pcuenca** [comment]
Actually, if we are going to support iOS we'd need to update the icon file for iOS instead of removing the icon. Let me open a PR for that.
